name: Preview Package
on:
    pull_request:
    push:
      branches-ignore:
        - main
      tags:
        - "!**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build
        run: pnpm build

      - run: pnpm dlx pkg-pr-new publish './packages/result' --comment=update --packageManager=pnpm